#!/usr/bin/env bash

# Extract required variables for Blue-Action partners
# at required time frequency
# runs on postprocessed output generated by ece-postprocess

# start and end year
start_year=1979
end_year=2015

# filename definitions
basename="ECE"
expname=$1  # experiment name

# variables
monthlyVars="MSL SP T CP LSP STR SSR SLHF SSHF TTR TSR T2M Z U V Q"
dailyVars="MSL T SSHF T2M Z U V"

# directories
inputdir=$2
outputdir=${inputdir}/extracted
workdir=${inputdir}/tmp

#reference time
cdoreftime="setreftime,1979-01-01,03:00"

# create output directory
if [ ! -d ${outputdir} ]; then
  mkdir -p ${outputdir}
fi

# extract daily variables
for var in ${dailyVars}; do
  for yr in $(seq ${start_year} ${end_year}); do
    outfile="${basename}_${expname}_${var}_daily_${yr}.nc"
    if [ -f ${outputdir}/${outfile} ] ; then
      continue
    fi
    rm -rf ${workdir}
    mkdir -p ${workdir}
    for mnth in $(seq -f "%02g" 1 12); do
      dt=${yr}${mnth}
      tmpfile="${basename}_${expname}_${var}_daily_${dt}.nc"
      if [ ! -f  ${workdir}/${tmpfile} ]; then
        cdo selvar,${var} ${inputdir}/ECE_${expname}_${dt}.nc ${workdir}/tmp.nc
        if [ ${var}=="CP" ] || [ ${var}=="LSP" ]; then 
          cdo daysum -shifttime,-1sec ${workdir}/tmp.nc ${workdir}/tmp2.nc
        else
          cdo daymean -shifttime,-1sec ${workdir}/tmp.nc ${workdir}/tmp2.nc
        fi
        cdo shifttime,1sec ${workdir}/tmp2.nc ${workdir}/tmp3.nc
        cdo ${cdoreftime} ${workdir}/tmp3.nc ${workdir}/${tmpfile}
        rm -f ${workdir}/tmp*.nc
      fi
    done
    cdo mergetime ${workdir}/${basename}_${expname}_${var}_daily_${yr}*.nc ${outputdir}/${outfile}
  done
done

# extract montly variables
for var in ${monthlyVars}; do
  for yr in $(seq ${start_year} ${end_year}); do
    outfile="${basename}_${expname}_${var}_monthly_${yr}.nc"
    if [ -f ${outputdir}/${outfile} ] ; then
      continue
    fi
    rm -rf ${workdir}
    mkdir -p ${workdir}
    for mnth in $(seq -f "%02g" 1 12); do
      dt=${yr}${mnth}
      tmpfile="${basename}_${expname}_${var}_monthly_${dt}.nc"
      if [ ! -f  ${workdir}/${tmpfile} ]; then
        cdo selvar,${var} ${inputdir}/ECE_${expname}_${dt}.nc ${workdir}/tmp.nc
        if [ ${var}=="CP" ] || [ ${var}=="LSP" ]; then
          cdo daysum -shifttime,-1sec ${workdir}/tmp.nc ${workdir}/tmp2.nc
        else
          cdo daymean -shifttime,-1sec ${workdir}/tmp.nc ${workdir}/tmp2.nc
        fi
        cdo shifttime,1sec ${workdir}/tmp2.nc ${workdir}/tmp3.nc
        if [ ${var}=="CP" ] || [ ${var}=="LSP" ]; then
          cdo monsum ${workdir}/tmp3.nc ${workdir}/tmp4.nc
        else
          cdo monmean ${workdir}/tmp3.nc ${workdir}/tmp4.nc
        fi
        cdo ${cdoreftime} ${workdir}/tmp4.nc ${workdir}/${tmpfile}
        rm -f ${workdir}/tmp*.nc
      fi
    done
    cdo mergetime ${workdir}/${basename}_${expname}_${var}_monthly_${yr}*.nc ${outputdir}/${outfile}
  done
done
